name: shoe_quest
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2


dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.3.0
  intl: ^0.20.2
  logger: ^2.0.1
  url_launcher: ^6.0.6
  flutter_native_splash: ^2.4.5
  smooth_page_indicator: ^1.2.1
  carousel_slider: ^5.0.0

  # Icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8


  # State Management
  get: ^4.3.8
  get_storage: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0


flutter:

 
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/images/banners/
    - assets/icons/categories/
    - assets/icons/payment_methods/


